spring:
  application:
    name: SnackOrdering
    security:
      jwt:
        access_token:
          secret: de2a11b64cb8a10bbfa6ca0a4afb3578cc434cda024b8817b0cf98e38b61b9f3
          expiration: 600000
        refresh_token:
          secret: 85ec7a7e649be00c51fe797ae418fc06aa5fc0a80f90afa674eac1a8521e0832
          expiration: 604800000
      sms-otp:
        twilio-account-sid:
        twilio-auth-token:
        twilio-service-sid:
  datasource:
    url: jdbc:mysql://localhost:3306/snack_ordering
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true